image: nettojulio/ci-cd-e8:java-maven

stages:
  - build
  - test
  - push-docker
  - deploy

build:
  stage: build
  script:
    - echo "Clean the code..."
    - mvn clean
    - echo "Compiling the code..."
    - mvn package -Dmaven.test.skip
    - echo "Compile complete."

test:
  stage: test
  script:
    - PRIVATE_KEY=$PRIVATE_KEY RDS_HOSTNAME=$RDS_HOSTNAME RDS_ADMIN_DB_NAME=$RDS_ADMIN_DB_NAME RDS_PASSWORD=$RDS_PASSWORD RDS_PORT=$RDS_PORT RDS_USERNAME=$RDS_USERNAME SECRET_KEY=$SECRET_KEY mvn test
    - echo "Test OK!"

push-image:
  image: docker
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  stage: push-docker
  dependencies:
    - test
  script:
    - docker build -t nettojulio/api-administrador-e8:cicdtest -f Dockerfile . # ATENCAO COM A TAG
    - docker push nettojulio/api-administrador-e8:cicdtest # ATENCAO COM A TAG

deploy:
  stage: deploy
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
