apiVersion: v1
kind: Service
metadata:
  name: load-balancer-api-administrador-e8
  namespace: grupo-08-prod
spec:
  selector:
    app: api-administrador-e8
  ports:
    - protocol: 'TCP'
      port: 8080
      targetPort: 8080
  type: LoadBalancer